### ISSUE TITLE
Issue using the taxonomy filter inside a tag

### ISSUE THREAD

**Issue by iamdarkle** [flamarkt/taxonomies#1]
I've finally given taxonomies for discussions a try, what a wonderful extension! I definitely think it will become very popular, the ability for users to write their own taxonomies is great. 

Maybe I'm rushing to report this as I believe there is no official release yet, but I've detected a small bug when using the taxonomy homepage filters within a tag (main or secondary), when doing this the taxonomy filter works but skips the tag requirement.

**Comment by clarkwinkelmann** [comment]
It's very close to having its first release!

There's actually still a TODO comment for this particular thing in the code.

Unfortunately Flarum's filter system only allows one filter of a given type per request, which is problematic for the use case of this extension. I'll need to come up with some solution before the first release...

**Comment by clarkwinkelmann** [comment]
This is now partially fixed on `main` branch.

There's still an issue with tag permalinks that include a `?q=` parameter, but it's actually a Flarum issue and not specific to this extension. Flarum either applies the tag or the search, but not both.

**Comment by iamdarkle** [comment]
I've upgraded, it works smoothly! I noticed this, when you add a second taxonomy type or more the taxonomy links in the discussion hero stop working, honestly I hadn't noticed this before, so I'm not sure if it's a new version thing, I wish I could confirm it, but I'm not sure how to roll back a dev version 😅

**Comment by clarkwinkelmann** [comment]
This has been fixed in version 0.1
