### ISSUE TITLE
Problem with the composer when opening/closing it

### ISSUE THREAD

**Issue by iamdarkle** [flamarkt/taxonomies#7]
I noticed a bug, for some reason when this extension is enabled, if you open the composer to write a discussion, and you close it (by clicking on the cross), when you try to open it again, the "Start a Discussion" button won't work (doesn't do anything), so you will have to do a full refresh of the page, in the console there is no error about it.

**Comment by clarkwinkelmann** [comment]
I am unable to replicate on either Flarum 1.4 or 1.5.

Can you share your `php flarum info` output?

**Comment by iamdarkle** [comment]
I think I have found the extension that causes this conflict with taxonomies, could you try again with `fof/drafts` enabled?

I'm testing it in 1.5, if you can't reproduce it either, I'll pass you the `php flarum info`, although it's very long so I've tested one by one to make the task a bit easier, I'd say it's `fof/drafts`.

**Comment by Danter3** [comment]
The same thing is happening to me, is there any solution? I was just starting to use taxonomies but having to remove fof/drafts to make the compositior work properly is not very convenient...

**Comment by iamdarkle** [comment]
Unfortunately I don't know any solution, I still suffer from this issue, some time ago out of curiosity I tried with the Direct Links extension (https://discuss.flarum.org/d/25767-direct-links) to see if it also goes through the links and if it also does, that rules out something I was suspicious about...

**Comment by clarkwinkelmann** [comment]
Fixed in version 0.1.9 of Taxonomies. Taxonomies are now also saved with the draft.

**Comment by Danter3** [comment]
Thanks @clarkwinkelmann I'm delighted to finally be able to use taxonomies 🙂
